### ISSUE TITLE
Error message while running the damn thing

### ISSUE THREAD

**Issue by malin2** [jonkpirateboy/Pass-fur-alle#33]
Hi!

I get this error message "Service chromedriver unexpectedly exited. Status code was: 1". Any tips on why this is happening?

I'm using a windows computer

**Comment by jonkpirateboy** [comment]
I guess chromedriver just crashed, try running again.

**Comment by andnil84** [comment]
I get the same problem...
Is Chromedriver correctly installed?
(Very new to this...)
Running on Win11

andnil84@DESKTOP-HJQCGIS:/mnt/c/users/andni/downloads$ python3 pass-fur-alle.py
Traceback (most recent call last):
  File "pass-fur-alle.py", line 18, in <module>
    web = webdriver.Chrome(options=options)
  File "/home/andnil84/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/andnil84/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/home/andnil84/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/andnil84/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1

**Comment by jonkpirateboy** [comment]
This is now closed since Pass für alle has changed from Python to Javascript
