### ISSUE TITLE
RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!

### ISSUE THREAD

**Issue by alexljung** [jonkpirateboy/Pass-fur-alle#44]
Have an issue when rubning it in wsl. 

Full stack trace below. 

Folled the instructions in the README

  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "pass-fur-alle.py", line 15, in <module>
    web = webdriver.Chrome(options=options)
  File "/home/xzay/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/xzay/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/home/xzay/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/xzay/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127

**Comment by jonkpirateboy** [comment]
This is now closed since Pass für alle has changed from Python to Javascript
